version: '3.8'

services:
  db:
    image: postgres:13.10
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../wallets/
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db

volumes:
  pg_data: