services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: wallets/Dockerfile
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate;
             gunicorn wallets.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./wallets:/app

volumes:
  pg_data:
